export const dismissReasons = [
  ["wrong_edition_version", "Wrong Edition / Version"],
  ["wrong_product", "Wrong Product"],
  ["seller_listing_mismatch", "Seller Listing Does Not Match Photos"],
  ["no_longer_available", "No Longer Available"],
  ["missing_shrink_wrap", "Missing Shrink Wrap"],
  ["sales_velocity_too_low", "Sales Velocity Too Low"],
  ["wrong_platform", "Wrong Platform"],
  ["digital_item", "Digital Item"],
  ["incomplete_product", "Incomplete Product"],
  ["packaging_damage", "Packaging Damage"],
  ["non_north_american_version", "Non-North-American Version"],
  ["other", "Other"],
  ["roi_too_low", "ROI Too Low"],
  ["suspected_reseal", "Suspected Reseal"],
  ["nfr", "NFR"],
] as const;
