import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import ts from "typescript";
const out={};new Function("exports",ts.transpileModule(readFileSync(new URL("./sourcingResourceCache.ts",import.meta.url),"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(out);
const {SourcingResourceCache,sourcingTabUrls}=out;
let version="v1",running=false;const calls=[];let deferred=null;
const transport=async url=>{
 calls.push(url);
 if(url.includes("cache-version"))return Response.json({version,running});
 if(deferred)return new Promise(resolve=>deferred.push(resolve));
 return Response.json({value:url,cacheVersion:version});
};
const cache=new SourcingResourceCache(transport),url="/api/sourcing/opportunities?format=list&status=open";
assert.equal((await (await cache.get(url)).json()).cacheVersion,"v1");
const startCount=calls.length;const oldNow=Date.now;Date.now=()=>oldNow()+20*60*60*1000;
await cache.get(url);assert.equal(calls.length,startCount,"No TTL expiry: a stable run remains cached for hours");Date.now=oldNow;
version="v2";await cache.checkVersion();await cache.get(url);assert.equal(calls.length,startCount+2,"Changed database revision invalidates");
cache.invalidate();await cache.get(url);assert.equal(calls.length,startCount+3,"Operator mutation invalidates");
await cache.get(url,{fresh:true});assert(calls.at(-1).includes("fresh=1"));
cache.invalidate();deferred=[];
const first=cache.get(url),second=cache.get(url);await new Promise(r=>setImmediate(r));assert.equal(deferred.length,1,"Requests coalesce");deferred[0](Response.json({cacheVersion:version}));await Promise.all([first,second]);
cache.invalidate();deferred=[];const stale=cache.get(url);await new Promise(r=>setImmediate(r));cache.invalidate();deferred[0](Response.json({cacheVersion:version}));await assert.rejects(stale,/changed while loading/);
deferred=null;running=true;await cache.checkVersion();const count=calls.length;await cache.get(url);await cache.get(url);assert.equal(calls.length,count+2,"Active runs do not reuse cached lists");running=false;await cache.checkVersion();
const backgroundCalls=[];const bg=new SourcingResourceCache(async url=>{backgroundCalls.push(url);return Response.json(url.includes('cache-version')?{version:'bg',running:false}:{cacheVersion:'bg'});});
const stop=bg.start();await bg.checkVersion();assert.equal(backgroundCalls.length,1,"Entering sourcing checks only lightweight freshness");
await bg.get(url);assert.equal(backgroundCalls.length,2,"Buy List is the first data request");bg.prefetchAfterBuyList();assert.equal(backgroundCalls.length,2,"Background loading yields for Buy List paint");
await new Promise(r=>setTimeout(r,1400));assert.equal(backgroundCalls.length,2+sourcingTabUrls.length,"Every remaining tab preloads");
const before=backgroundCalls.length;await bg.get(sourcingTabUrls[0]);assert.equal(backgroundCalls.length,before,"Tab consumes prefetched result");stop();
let attempts=0;const failure=new SourcingResourceCache(async url=>url.includes('cache-version')?Response.json({version:'v',running:false}):(attempts++,Response.json({error:'Actual failure'},{status:500})));
assert.equal((await (await failure.get('/api/sourcing/settings')).json()).error,'Actual failure');await failure.get('/api/sourcing/settings');assert.equal(attempts,2,'Errors are never cached');
console.log('Resource cache: long-lived hits, revision and mutation invalidation, force refresh, single-flight, stale rejection, active runs, Buy List first, all-tab preload and errors passed');
