export type SourcingOpportunity = {
  opportunityId: string;
  runId: string;
  asin: string;
  amazonTitle: string;
  amazonImageUrl: string | null;
  sellerSku: string | null;
  sourceMode: string | null;
  amazonUrl: string;
  ebayItemId: string | null;
  ebayLegacyItemId: string | null;
  ebayUrl: string | null;
  ebayTitle: string;
  ebayImageUrl: string | null;
  sellerUsername: string | null;
  itemLocationCountry: string | null;
  conditionName: string | null;
  buyingOptions: string[];
  itemPrice: number | null;
  shippingPrice: number | null;
  landedCost: number | null;
  originalCurrency: string | null;
  originalItemPrice: number | null;
  originalShippingPrice: number | null;
  shippingQuoteStatus: "known_paid" | "known_free" | "unknown_no_cost" | "unknown_no_options";
  shippingQuoteLabel: string;
  quantityAvailable: number | null;
  auctionEndAt: string | null;
  bidCount: number | null;
  bestOfferEnabled: boolean;
  targetSalePrice: number | null;
  lastSalePrice: number | null;
  keepaAvg90Price: number | null;
  keepaAvg90Label: string | null;
  keepaCurrentPrice: number | null;
  keepaCurrentPriceLabel: string | null;
  currentInventoryUnits: number | null;
  monthlyVelocity: number | null;
  monthsOfSupply: number | null;
  inventoryNeedLevel: string | null;
  lastSoldAt: string | null;
  opportunityType: string | null;
  status: string | null;
  estimatedProfit: number | null;
  estimatedRoiPercent: number | null;
  maxProfitableLandedCost: number | null;
  suggestedOfferPrice: number | null;
  requiredOfferPercentOfAsk: number | null;
  suggestedMaxBid: number | null;
  quantityMultiplier: number | null;
  totalProfitOpportunity: number | null;
  score: number | null;
  aiFlags: string[];
  matchingDiagnostics: unknown;
  createdAt: string | null;
};

export type SourcingSettings = {
  setting_id?: string;
  min_amazon_price: number;
  min_roi_percent: number;
  min_profit_dollars: number;
  sales_lookback_days: number;
  inventory_need_months_threshold: number;
  buyer_zip: string;
  buyer_country: string;
  item_location_countries: string[];
  delivery_country: string;
  best_offer_min_ask_percent: number;
  excluded_keywords: string[];
};

export type SourcingRun = {
  sourcing_run_id: string;
  run_type: string;
  status: string;
  started_at: string | null;
  completed_at: string | null;
  seed_asin_count: number | null;
  ebay_candidate_count: number | null;
  opportunity_count: number | null;
  error_message?: string | null;
};
