import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const out={};new Function('exports',ts.transpileModule(readFileSync(new URL('./deliveryStats.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(out);
const data={notDelivered:{units:7,purchaseDollars:123.45,unpricedUnits:0},deliveredNotReceived:{units:3,purchaseDollars:99,unpricedUnits:1}};
const saturday={throughDate:'2026-09-19',units:4,purchaseDollars:88.5,unpricedUnits:0};
assert.deepEqual((await out.fetchDeliveryStats({rpc:async name=>name==='purchase_delivery_stats'?{data,error:null}:{data:saturday,error:null}})).delivery,{...data,dueBySaturday:saturday});
assert.deepEqual(await out.fetchDeliveryStats({rpc:async()=>({data:null,error:{message:'Actual DB failure'}})}),{delivery:null,deliveryError:'Actual DB failure',deliveryDueError:null});
assert.equal((await out.fetchDeliveryStats({rpc:async()=>({data:{},error:null})})).delivery,null);
const partial=await out.fetchDeliveryStats({rpc:async name=>name==='purchase_delivery_stats'?{data,error:null}:{data:null,error:{message:'ETA failed'}}});
assert.deepEqual(partial,{delivery:data,deliveryError:null,deliveryDueError:'ETA failed'});
console.log('Purchase delivery API: authoritative totals preserved; actual errors and invalid results visible, never zero-filled');
