from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXPORTS = ROOT / "exports"


COMMON_SUPABASE = "SUPABASE_URL; SUPABASE_SERVICE_ROLE_KEY"
AMAZON_SPAPI = (
    "AMAZON_SP_API_CLIENT_ID; AMAZON_SP_API_CLIENT_SECRET; "
    "AMAZON_SP_API_REFRESH_TOKEN; AMAZON_SP_API_MARKETPLACE_ID; "
    "AMAZON_SP_API_AWS_ACCESS_KEY_ID/AWS_ACCESS_KEY_ID; "
    "AMAZON_SP_API_AWS_SECRET_ACCESS_KEY/AWS_SECRET_ACCESS_KEY; "
    "AMAZON_SP_API_SELLER_ID/AMAZON_SELLER_ID for listing calls"
)
EBAY = "EBAY_CLIENT_ID; EBAY_CLIENT_SECRET; EBAY_REFRESH_TOKEN"
KEEPA = "KEEPA_API_KEY; optional KEEPA_API_ENDPOINT; optional KEEPA_DOMAIN_ID"
EASYPOST = "EASYPOST_API_KEY"
YNAB = "YNAB_PERSONAL_TOKEN or YNAB_ACCESS_TOKEN; optional YNAB_PLAN_NAME; optional YNAB_BUSINESS_CATEGORY_NAME"


JOBS = [
    {
        "job name": "eBay buyer purchases",
        "command/script": "integrations/ebay_sync_buyer_purchases.py --days-back 7 --missing-tracking-lookback-days 90 --missing-tracking-limit 250",
        "current group(s)": "core; purchases; dashboard",
        "reads tables": "purchases; purchase_items; inbound_shipments",
        "writes tables": "import_batches; purchases; purchase_items; inbound_shipments; inbound_shipment_items",
        "external services used": "eBay Trading API; eBay Browse API; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {EBAY}",
        "must run after": "none",
        "should run after": "Supabase preflight succeeds",
        "must not overlap with": "itself; EasyPost shipments; eBay order problem returns/inquiries; receiving edits that update purchase_items.current_status",
        "safe to run independently": "yes",
        "safe to parallelize": "limited: can run beside Amazon/YNAB/Informed jobs, but avoid parallel purchase/inbound shipment writers",
        "incremental vs bounded lookback vs broad/backfill-style": "bounded lookback plus 90-day missing-tracking refresh",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "purchase-ingestion",
        "recommended initial frequency": "hourly during workday; every 2-4 hours off-hours",
        "notes/risks": "Root purchase source. Downstream purchase matching and inbound tracking depend on fresh purchase/inbound rows. eBay quota and 90-day missing-tracking query are the main external/load risks.",
    },
    {
        "job name": "Sourcing purchase matching",
        "command/script": "integrations/match_sourcing_purchases.py --limit 300",
        "current group(s)": "core; purchases; dashboard",
        "reads tables": "sourcing_opportunities; sourcing_ebay_candidates; sourcing_seed_asins; vw_latest_keepa_product_snapshot; sourcing_actions; purchases; purchase_items",
        "writes tables": "sourcing_purchase_matches; purchase_items; sourcing_opportunities; sourcing_actions",
        "external services used": "Supabase-only",
        "required secrets/env vars": COMMON_SUPABASE,
        "must run after": "eBay buyer purchases",
        "should run after": "Keepa active products; RevSeller enrichment, when catalog/title quality matters",
        "must not overlap with": "itself; other sourcing match/rescore jobs that mutate sourcing_opportunities",
        "safe to run independently": "yes, but less useful before purchase ingestion",
        "safe to parallelize": "limited: avoid parallel sourcing mutation jobs",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental limited batch",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "purchase-ingestion",
        "recommended initial frequency": "hourly, immediately after eBay purchase ingestion",
        "notes/risks": "Connects accepted sourcing opportunities to imported eBay purchases. Keepa data improves target price context but is not a hard dependency.",
    },
    {
        "job name": "EasyPost shipments",
        "command/script": "integrations/easypost_sync_shipments.py --limit 150",
        "current group(s)": "core; purchases; dashboard",
        "reads tables": "purchases; purchase_items; inbound_shipments; inbound_shipment_items",
        "writes tables": "inbound_shipments; inbound_shipment_items; purchase_items",
        "external services used": "EasyPost; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {EASYPOST}",
        "must run after": "eBay buyer purchases",
        "should run after": "eBay order problem returns/inquiries, for return-created inbound shipments; but inbound purchase tracking can run before it",
        "must not overlap with": "itself; eBay buyer purchases; eBay order problem returns/inquiries, because all can create/update inbound_shipments",
        "safe to run independently": "yes, when candidate inbound shipments already exist",
        "safe to parallelize": "limited: avoid other inbound shipment writers",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental limited batch; prioritizes non-delivered rows",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "purchase-tracking",
        "recommended initial frequency": "hourly for inbound purchases",
        "notes/risks": "Has 5 requests/sec cap and 429 backoff. Long-term, EasyPost webhooks should replace frequent polling for active trackers.",
    },
    {
        "job name": "eBay order problem returns/inquiries",
        "command/script": "integrations/ebay_sync_order_problem_returns.py --lookback-days 60 --limit 100 --apply",
        "current group(s)": "core; purchases; dashboard",
        "reads tables": "purchases; purchase_items; inbound_shipments; order_problem_cases",
        "writes tables": "order_problem_cases; order_problem_events; inbound_shipments; inbound_shipment_items; purchase_items",
        "external services used": "eBay Post-Order API; eBay Trading API; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {EBAY}",
        "must run after": "eBay buyer purchases",
        "should run after": "EasyPost shipments, if latest delivered status should inform problem state review",
        "must not overlap with": "itself; EasyPost order problem returns; EasyPost shipments; eBay buyer purchases",
        "safe to run independently": "yes, but matching quality depends on existing purchases/purchase_items",
        "safe to parallelize": "limited: avoid order_problem_cases/inbound shipment writers",
        "incremental vs bounded lookback vs broad/backfill-style": "bounded 60-day lookback limited to 100",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "returns-and-order-problems",
        "recommended initial frequency": "every 2-4 hours",
        "notes/risks": "Nonblocking in current scheduler. Writes order-problem events and can set purchase item statuses such as Return Opened/Pending.",
    },
    {
        "job name": "EasyPost order problem returns",
        "command/script": "integrations/easypost_sync_order_problem_returns.py --limit 100",
        "current group(s)": "core; purchases; dashboard",
        "reads tables": "order_problem_cases",
        "writes tables": "order_problem_cases; order_problem_events",
        "external services used": "EasyPost; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {EASYPOST}",
        "must run after": "eBay order problem returns/inquiries",
        "should run after": "none",
        "must not overlap with": "itself; eBay order problem returns/inquiries",
        "safe to run independently": "yes, if cases already have return tracking",
        "safe to parallelize": "limited: avoid order_problem_cases writers",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental limited batch",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "returns-and-order-problems",
        "recommended initial frequency": "every 2-4 hours; webhook-driven later",
        "notes/risks": "Should follow the eBay problem sync so new return tracking rows are visible.",
    },
    {
        "job name": "RevSeller enrichment",
        "command/script": "integrations/sync_revseller_sheet.py --ai-review --ai-review-limit 25",
        "current group(s)": "core; purchases; dashboard",
        "reads tables": "manual_item_matches; purchase_items; vw_latest_keepa_product_snapshot; vw_latest_amazon_listing_snapshot",
        "writes tables": "purchase_items; local diagnostics CSV",
        "external services used": "Google Sheets; optional OpenAI; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; GOOGLE_APPLICATION_CREDENTIALS; REVSELLER_GOOGLE_SHEET_ID; optional REVSELLER_WORKSHEET_NAME; optional OPENAI_API_KEY; optional OPENAI_MATCHING_MODEL",
        "must run after": "eBay buyer purchases",
        "should run after": "Keepa active products; Amazon listing status",
        "must not overlap with": "itself; manual purchase-item correction tools",
        "safe to run independently": "yes",
        "safe to parallelize": "limited: avoid purchase_items enrichment writers",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental enrichment scan",
        "whether safe for AWS cloud mode": "yes if Google service-account credential is supplied as an ECS secret/file; local diagnostics are unavailable unless redirected",
        "recommended AWS orchestration group": "purchase-enrichment",
        "recommended initial frequency": "hourly or every 2 hours after purchase ingestion",
        "notes/risks": "System/title matching must remain platform-specific. OpenAI use is capped by --ai-review-limit.",
    },
    {
        "job name": "Keepa missing purchase titles",
        "command/script": "integrations/backfill_amazon_titles_from_keepa.py --limit 25 --fetch-missing --min-tokens 25 --apply",
        "current group(s)": "core; purchases; dashboard",
        "reads tables": "purchase_items; purchases; vw_latest_keepa_product_snapshot",
        "writes tables": "purchase_items; keepa_product_snapshots via Keepa fetch path when needed",
        "external services used": "Keepa; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {KEEPA}",
        "must run after": "eBay buyer purchases",
        "should run after": "Keepa active products",
        "must not overlap with": "other Keepa jobs; RevSeller enrichment/manual title edits",
        "safe to run independently": "yes, with token guard",
        "safe to parallelize": "no with other Keepa jobs; limited with purchase_items writers",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental limited backfill",
        "whether safe for AWS cloud mode": "yes, but token-budget sensitive",
        "recommended AWS orchestration group": "purchase-enrichment",
        "recommended initial frequency": "every 4-6 hours or after purchase ingestion when missing-title count is nonzero",
        "notes/risks": "Despite backfill name it is part of current normal scheduler and bounded by --limit. Keepa token guard is low at 25.",
    },
    {
        "job name": "Amazon sales orders",
        "command/script": "integrations/amazon_sync_sales_orders.py --apply",
        "current group(s)": "core; sales-orders",
        "reads tables": "amazon_sales_orders; amazon_sales_order_items",
        "writes tables": "amazon_sales_orders; amazon_sales_order_items",
        "external services used": "Amazon SP-API Orders; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {AMAZON_SPAPI}",
        "must run after": "none",
        "should run after": "Supabase preflight succeeds",
        "must not overlap with": "itself; Amazon sales finance/profit jobs for same recent window if strict snapshot consistency is needed",
        "safe to run independently": "yes",
        "safe to parallelize": "limited: avoid overlapping with downstream sales-finance/profit chain; can run beside purchase/FBA jobs",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental default lookback",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "amazon-sales-recent",
        "recommended initial frequency": "hourly",
        "notes/risks": "Downstream sales finance and profitability should follow it. Item calls multiply SP-API usage for changed orders.",
    },
    {
        "job name": "Recent Amazon sales finances",
        "command/script": "integrations/amazon_sync_sales_finances.py --purchase-date-start days_ago(14) --order-finance-delay-seconds 1.5 --apply",
        "current group(s)": "core; sales-orders",
        "reads tables": "amazon_sales_orders; vw_amazon_sales_orders_recent",
        "writes tables": "amazon_sales_financial_events; amazon_sales_transactions",
        "external services used": "Amazon SP-API Finances/Transactions; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {AMAZON_SPAPI}",
        "must run after": "Amazon sales orders",
        "should run after": "wait long enough for Amazon fees to settle",
        "must not overlap with": "itself; Amazon missing-fee sales finances; Amazon sales finances audit",
        "safe to run independently": "yes, but only useful after sales orders exist",
        "safe to parallelize": "no with other sales-finance jobs; yes with unrelated domains",
        "incremental vs bounded lookback vs broad/backfill-style": "bounded 14-day lookback",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "amazon-sales-recent",
        "recommended initial frequency": "hourly or every 2 hours after sales orders",
        "notes/risks": "Observed as one of the long recent jobs. Raw financial event rows can be high volume. SP-API 429/retry behavior observed.",
    },
    {
        "job name": "Veeqo MF label costs",
        "command/script": "integrations/veeqo_sync_sales_labels.py --purchase-date-start days_ago(14) --missing-only --apply",
        "current group(s)": "core; sales-orders",
        "reads tables": "amazon_sales_orders; veeqo_sales_orders",
        "writes tables": "veeqo_sales_orders; veeqo_sales_shipments",
        "external services used": "Veeqo; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; VEEQO_KEY or VEEQO_API_KEY or VEEQO_ACCESS_TOKEN",
        "must run after": "Amazon sales orders",
        "should run after": "none",
        "must not overlap with": "itself",
        "safe to run independently": "yes, but needs Amazon order ids",
        "safe to parallelize": "yes with non-Veeqo jobs; avoid duplicate Veeqo runs",
        "incremental vs bounded lookback vs broad/backfill-style": "bounded 14-day lookback; missing-only",
        "whether safe for AWS cloud mode": "yes; exits skipped if Veeqo key missing",
        "recommended AWS orchestration group": "amazon-sales-recent",
        "recommended initial frequency": "hourly or every 2 hours after sales orders",
        "notes/risks": "Retries 429/5xx. Needed before best MF profitability numbers.",
    },
    {
        "job name": "Recent sales profitability",
        "command/script": "integrations/amazon_sales_profitability.py --purchase-date-start days_ago(14) --apply",
        "current group(s)": "core",
        "reads tables": "amazon_sales_orders; vw_amazon_sales_orders_recent; amazon_sales_order_items; amazon_sales_financial_events; veeqo_sales_shipments; amazon_sales_fulfillment_cost_overrides; amazon_sales_cogs_consumption; vw_latest_inventorylab_inventory_valuation; inventorylab_active_inventory_backfill",
        "writes tables": "amazon_sales_profitability; amazon_sales_cogs_consumption",
        "external services used": "Supabase-only",
        "required secrets/env vars": COMMON_SUPABASE,
        "must run after": "Amazon sales orders; Recent Amazon sales finances",
        "should run after": "Veeqo MF label costs; InventoryLab valuation imports/backfills if refreshed separately",
        "must not overlap with": "itself; Daily missing-fee sales profitability; Sales profitability audit; FIFO COGS repair scripts",
        "safe to run independently": "yes, but results are incomplete before upstream sales/finance/labels",
        "safe to parallelize": "no with other profitability writers",
        "incremental vs bounded lookback vs broad/backfill-style": "bounded 14-day lookback",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "amazon-sales-recent",
        "recommended initial frequency": "hourly after finance/label jobs",
        "notes/risks": "Backend-owned cost/profit calculation. Do not move landed/profit calculation to frontend.",
    },
    {
        "job name": "Amazon FBA inventory",
        "command/script": "integrations/amazon_sync_fba_inventory.py --page-delay-seconds 0.25",
        "current group(s)": "daily; dashboard; reconciliation; repricing; fba",
        "reads tables": "none before write, aside from Supabase connection",
        "writes tables": "amazon_skus; amazon_fba_inventory_snapshots",
        "external services used": "Amazon SP-API FBA Inventory; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {AMAZON_SPAPI}",
        "must run after": "none",
        "should run after": "Supabase preflight succeeds",
        "must not overlap with": "itself; Amazon listing status if both update amazon_skus heavily",
        "safe to run independently": "yes",
        "safe to parallelize": "limited: can run beside sales/purchase jobs; avoid multiple amazon_skus writers",
        "incremental vs bounded lookback vs broad/backfill-style": "broad snapshot",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "fba-inventory-daily",
        "recommended initial frequency": "daily; optional manual pre-reconciliation refresh",
        "notes/risks": "Observed 6,329 summaries and snapshots. Snapshot table growth and SP-API 429s are real; keep separate from listing audit.",
    },
    {
        "job name": "Amazon FBA shipments",
        "command/script": "integrations/amazon_sync_fba_shipments.py",
        "current group(s)": "daily; dashboard; reconciliation; fba",
        "reads tables": "fba_shipments; fba_shipment_items; amazon_skus",
        "writes tables": "fba_shipments; fba_shipment_items; fba_shipment_events",
        "external services used": "Amazon SP-API FBA Inbound; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {AMAZON_SPAPI}",
        "must run after": "none",
        "should run after": "Amazon FBA inventory, for SKU metadata and latest availability context",
        "must not overlap with": "itself; FBA EasyPost carrier tracking; manual FBA workflow edits",
        "safe to run independently": "yes",
        "safe to parallelize": "limited: avoid FBA shipment writers",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental limited shipment sync plus discovery",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "fba-shipments",
        "recommended initial frequency": "every 2-4 hours while shipment prep/transit is active; daily otherwise",
        "notes/risks": "Writes workflow events and shipment/item state. Should stay separate from purchases/receiving workflow.",
    },
    {
        "job name": "FBA EasyPost carrier tracking",
        "command/script": "integrations/easypost_sync_fba_shipments.py --limit 25 --max-new-trackers 10",
        "current group(s)": "daily; dashboard; reconciliation; fba",
        "reads tables": "fba_shipments",
        "writes tables": "fba_shipments; fba_shipment_events",
        "external services used": "EasyPost; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {EASYPOST}",
        "must run after": "Amazon FBA shipments, once tracking numbers exist",
        "should run after": "none",
        "must not overlap with": "itself; Amazon FBA shipments",
        "safe to run independently": "yes, if fba_shipments contain tracking",
        "safe to parallelize": "limited: avoid FBA shipment writers",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental limited batch",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "fba-shipments",
        "recommended initial frequency": "every 2-4 hours for in-transit FBA shipments; webhook-driven later",
        "notes/risks": "Bounded by --max-new-trackers. Uses EasyPost quota but small volume.",
    },
    {
        "job name": "Inventory reconciliation",
        "command/script": "integrations/inventory_reconcile.py --skip-if-unchanged",
        "current group(s)": "core; dashboard; reconciliation; fba",
        "reads tables": "purchase_items; vw_purchases_dashboard; fba_shipments; fba_shipment_items; amazon_skus; amazon_fba_inventory_snapshots; amazon_listing_snapshots; inventorylab_active_inventory_backfill",
        "writes tables": "inventory_positions; inventory_reconciliation_events; inventory_reconciliation_event_items",
        "external services used": "Supabase-only",
        "required secrets/env vars": COMMON_SUPABASE,
        "must run after": "Amazon FBA inventory",
        "should run after": "Amazon FBA shipments; Amazon listing status; eBay buyer purchases; EasyPost shipments",
        "must not overlap with": "itself; Inventory reconciliation audit",
        "safe to run independently": "yes, but skip-if-unchanged may skip when inputs unchanged",
        "safe to parallelize": "limited: read-heavy; avoid running with broad Supabase scans/audits",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental skip-if-unchanged, but broad table read when source timestamps change",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "reconciliation",
        "recommended initial frequency": "hourly after core purchase tracking and daily after FBA inventory; consider event-triggered fan-in",
        "notes/risks": "Reads many operational tables. Do not run concurrently with dashboard-heavy broad scans on constrained Supabase IO.",
    },
    {
        "job name": "Amazon listing status",
        "command/script": "integrations/amazon_sync_listing_status.py --active-only --stale-days 3",
        "current group(s)": "daily; dashboard; repricing",
        "reads tables": "amazon_skus; amazon_listing_snapshots",
        "writes tables": "amazon_listing_snapshots; amazon_skus",
        "external services used": "Amazon SP-API Listings Items; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {AMAZON_SPAPI}",
        "must run after": "Amazon FBA inventory",
        "should run after": "none",
        "must not overlap with": "itself; Amazon listing status audit; Amazon FBA inventory if amazon_skus load is high",
        "safe to run independently": "yes, if amazon_skus exists",
        "safe to parallelize": "limited: one Listings call per selected SKU; avoid other Listings-heavy jobs",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental stale active listings",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "repricing-catalog",
        "recommended initial frequency": "daily with stale-days=3; manual/audit weekly",
        "notes/risks": "Listings Items API is rate-limited. Normal job selected only stale rows; audit selected hundreds.",
    },
    {
        "job name": "Amazon inventory planning",
        "command/script": "integrations/amazon_sync_inventory_planning.py",
        "current group(s)": "daily; dashboard; repricing",
        "reads tables": "amazon_report_runs",
        "writes tables": "amazon_report_runs; amazon_inventory_planning_snapshots",
        "external services used": "Amazon SP-API Reports; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {AMAZON_SPAPI}",
        "must run after": "none",
        "should run after": "Amazon FBA inventory",
        "must not overlap with": "itself; other Amazon report request/poll jobs if report quota is tight",
        "safe to run independently": "yes",
        "safe to parallelize": "limited: avoid concurrent report-heavy jobs",
        "incremental vs bounded lookback vs broad/backfill-style": "broad report snapshot",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "fba-inventory-daily",
        "recommended initial frequency": "daily",
        "notes/risks": "Report polling can hold ECS task time. Writes point-in-time snapshot rows.",
    },
    {
        "job name": "YNAB Business transactions",
        "command/script": "integrations/ynab_sync_business_transactions.py --incremental --apply",
        "current group(s)": "daily; dashboard",
        "reads tables": "ynab_business_transactions",
        "writes tables": "ynab_business_transactions",
        "external services used": "YNAB; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {YNAB}",
        "must run after": "none",
        "should run after": "none",
        "must not overlap with": "itself",
        "safe to run independently": "yes",
        "safe to parallelize": "yes",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "finance-daily",
        "recommended initial frequency": "daily",
        "notes/risks": "Low volume. Should finish before business value snapshot if cash/transaction context is part of downstream reporting.",
    },
    {
        "job name": "YNAB cash balance",
        "command/script": "integrations/ynab_sync_cash_balance.py --apply",
        "current group(s)": "daily; dashboard",
        "reads tables": "none significant before write",
        "writes tables": "ynab_category_balance_snapshots",
        "external services used": "YNAB; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {YNAB}",
        "must run after": "none",
        "should run after": "YNAB Business transactions",
        "must not overlap with": "itself",
        "safe to run independently": "yes",
        "safe to parallelize": "yes",
        "incremental vs bounded lookback vs broad/backfill-style": "point-in-time snapshot",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "finance-daily",
        "recommended initial frequency": "daily before business value snapshot",
        "notes/risks": "Low volume. Business value snapshot reads latest YNAB balance view.",
    },
    {
        "job name": "Amazon finance balances",
        "command/script": "integrations/amazon_sync_finance_balances.py --apply",
        "current group(s)": "daily; dashboard",
        "reads tables": "ynab_business_transactions",
        "writes tables": "amazon_finance_balance_snapshots",
        "external services used": "Amazon SP-API Finances; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {AMAZON_SPAPI}; optional AMAZON_UNMATCHED_COMPLETED_TRANSFER_LOOKBACK_DAYS",
        "must run after": "none",
        "should run after": "YNAB Business transactions, for transfer matching context",
        "must not overlap with": "itself; heavy Amazon finance jobs when SP-API quota is tight",
        "safe to run independently": "yes",
        "safe to parallelize": "limited: avoid Amazon finance-heavy jobs",
        "incremental vs bounded lookback vs broad/backfill-style": "point-in-time finance snapshot with bounded transaction/event-group reads",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "finance-daily",
        "recommended initial frequency": "daily before business value snapshot",
        "notes/risks": "Feeds business value snapshot. SP-API finance calls are moderate.",
    },
    {
        "job name": "Amazon missing-fee sales finances",
        "command/script": "integrations/amazon_sync_sales_finances.py --purchase-date-start days_ago(60) --order-finance-delay-seconds 1.5 --missing-fees-only --apply",
        "current group(s)": "daily; sales-orders; dashboard",
        "reads tables": "amazon_sales_orders; vw_amazon_sales_orders_recent",
        "writes tables": "amazon_sales_financial_events; amazon_sales_transactions",
        "external services used": "Amazon SP-API Finances/Transactions; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {AMAZON_SPAPI}",
        "must run after": "Amazon sales orders",
        "should run after": "Recent Amazon sales finances",
        "must not overlap with": "Recent Amazon sales finances; Amazon sales finances audit",
        "safe to run independently": "yes, but should be separate from recent chain",
        "safe to parallelize": "no with other sales-finance jobs",
        "incremental vs bounded lookback vs broad/backfill-style": "bounded 60-day missing-only lookback",
        "whether safe for AWS cloud mode": "yes, but isolate as quota-sensitive",
        "recommended AWS orchestration group": "amazon-sales-fee-repair",
        "recommended initial frequency": "daily",
        "notes/risks": "Nonblocking today. Use lower priority/capacity than current sales freshness chain.",
    },
    {
        "job name": "Daily missing-fee sales profitability",
        "command/script": "integrations/amazon_sales_profitability.py --purchase-date-start days_ago(60) --missing-fees-only --apply",
        "current group(s)": "daily; sales-orders; dashboard",
        "reads tables": "amazon sales/order/finance/COGS/label tables",
        "writes tables": "amazon_sales_profitability; amazon_sales_cogs_consumption",
        "external services used": "Supabase-only",
        "required secrets/env vars": COMMON_SUPABASE,
        "must run after": "Amazon missing-fee sales finances",
        "should run after": "Veeqo MF label costs",
        "must not overlap with": "Recent sales profitability; Sales profitability audit",
        "safe to run independently": "yes, but useful only after missing-fee finance",
        "safe to parallelize": "no with profitability writers",
        "incremental vs bounded lookback vs broad/backfill-style": "bounded 60-day missing-only lookback",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "amazon-sales-fee-repair",
        "recommended initial frequency": "daily after missing-fee finance",
        "notes/risks": "Supabase-heavy relative to simple snapshots; keep out of hourly critical path.",
    },
    {
        "job name": "Amazon sales finances audit",
        "command/script": "integrations/amazon_sync_sales_finances.py --purchase-date-start days_ago(60) --order-finance-delay-seconds 1.5 --apply",
        "current group(s)": "finance-audit",
        "reads tables": "amazon_sales_orders; vw_amazon_sales_orders_recent",
        "writes tables": "amazon_sales_financial_events; amazon_sales_transactions",
        "external services used": "Amazon SP-API Finances/Transactions; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {AMAZON_SPAPI}",
        "must run after": "Amazon sales orders",
        "should run after": "none",
        "must not overlap with": "Recent Amazon sales finances; Amazon missing-fee sales finances; itself",
        "safe to run independently": "yes, but not in the critical schedule",
        "safe to parallelize": "no with sales-finance jobs",
        "incremental vs bounded lookback vs broad/backfill-style": "broad audit bounded 60-day lookback",
        "whether safe for AWS cloud mode": "yes, but manual/weekly only",
        "recommended AWS orchestration group": "finance-audit",
        "recommended initial frequency": "manual-only initially; weekly off-hours if needed",
        "notes/risks": "Longest observed job at ~21 minutes. Major SP-API quota/cost/runtime candidate.",
    },
    {
        "job name": "Sales profitability audit",
        "command/script": "integrations/amazon_sales_profitability.py --purchase-date-start days_ago(60) --apply",
        "current group(s)": "finance-audit",
        "reads tables": "amazon sales/order/finance/COGS/label tables",
        "writes tables": "amazon_sales_profitability; amazon_sales_cogs_consumption",
        "external services used": "Supabase-only",
        "required secrets/env vars": COMMON_SUPABASE,
        "must run after": "Amazon sales finances audit",
        "should run after": "Veeqo MF label costs",
        "must not overlap with": "Recent sales profitability; Daily missing-fee sales profitability; itself",
        "safe to run independently": "yes, but not in critical path",
        "safe to parallelize": "no with profitability writers",
        "incremental vs bounded lookback vs broad/backfill-style": "broad audit bounded 60-day lookback",
        "whether safe for AWS cloud mode": "yes, but manual/weekly only",
        "recommended AWS orchestration group": "finance-audit",
        "recommended initial frequency": "manual-only initially; weekly after finance audit if needed",
        "notes/risks": "Observed ~4.4 minutes. Supabase-heavy and not required for hourly freshness.",
    },
    {
        "job name": "Amazon listing status audit",
        "command/script": "integrations/amazon_sync_listing_status.py --active-only",
        "current group(s)": "listing-audit",
        "reads tables": "amazon_skus",
        "writes tables": "amazon_listing_snapshots; amazon_skus",
        "external services used": "Amazon SP-API Listings Items; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {AMAZON_SPAPI}",
        "must run after": "Amazon FBA inventory",
        "should run after": "none",
        "must not overlap with": "Amazon listing status; itself",
        "safe to run independently": "yes, but quota-heavy",
        "safe to parallelize": "no with listing-status jobs",
        "incremental vs bounded lookback vs broad/backfill-style": "broad active-listing audit",
        "whether safe for AWS cloud mode": "yes, but manual/weekly only",
        "recommended AWS orchestration group": "listing-audit",
        "recommended initial frequency": "manual-only initially; weekly off-hours if needed",
        "notes/risks": "One Listings Items call per active SKU. Observed 365 rows and 429/retry signals.",
    },
    {
        "job name": "Inventory reconciliation audit",
        "command/script": "integrations/inventory_reconcile.py",
        "current group(s)": "inventory-audit",
        "reads tables": "same as Inventory reconciliation",
        "writes tables": "inventory_positions; inventory_reconciliation_events; inventory_reconciliation_event_items",
        "external services used": "Supabase-only",
        "required secrets/env vars": COMMON_SUPABASE,
        "must run after": "Amazon FBA inventory; Amazon FBA shipments; Amazon listing status",
        "should run after": "purchase tracking jobs",
        "must not overlap with": "Inventory reconciliation; itself",
        "safe to run independently": "yes",
        "safe to parallelize": "limited: avoid broad Supabase jobs",
        "incremental vs bounded lookback vs broad/backfill-style": "broad audit",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "inventory-audit",
        "recommended initial frequency": "manual-only or weekly off-hours",
        "notes/risks": "No skip-if-unchanged. Keep off the critical scheduler unless explicitly auditing.",
    },
    {
        "job name": "Informed repricing reports",
        "command/script": "integrations/informed_sync_reports.py --write",
        "current group(s)": "daily; repricing",
        "reads tables": "informed_report_runs",
        "writes tables": "informed_report_runs; informed_listing_snapshots/informed_rule_snapshots depending report category",
        "external services used": "Informed Reports API; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; INFORMED_REPRICER_API_KEY; optional INFORMED_REPRICER_ENDPOINT",
        "must run after": "none",
        "should run after": "Amazon listing status; Keepa active products, for repricing dashboard context",
        "must not overlap with": "itself; other Informed report jobs",
        "safe to run independently": "yes",
        "safe to parallelize": "limited: report polling task can run beside non-repricing jobs",
        "incremental vs bounded lookback vs broad/backfill-style": "report snapshot",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "repricing-catalog",
        "recommended initial frequency": "daily",
        "notes/risks": "Read-only advisory intelligence. Must not use Informed Listings Management upload/feed APIs.",
    },
    {
        "job name": "Business value snapshot",
        "command/script": "integrations/business_value_snapshot.py --apply",
        "current group(s)": "daily; dashboard; fba",
        "reads tables": "inventory_positions; vw_latest_amazon_finance_balance_snapshot; vw_latest_ynab_category_balance_snapshot; business_value_snapshots",
        "writes tables": "business_value_snapshots",
        "external services used": "Supabase-only",
        "required secrets/env vars": COMMON_SUPABASE,
        "must run after": "Inventory reconciliation; YNAB cash balance; Amazon finance balances",
        "should run after": "Amazon FBA inventory; Amazon FBA shipments; Amazon inventory planning",
        "must not overlap with": "itself; inventory reconciliation writes if strict value snapshot consistency matters",
        "safe to run independently": "yes, but freshness depends on upstream snapshots",
        "safe to parallelize": "limited: run after finance/inventory fan-in for best numbers",
        "incremental vs bounded lookback vs broad/backfill-style": "point-in-time business value snapshot",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "business-value-finalizer",
        "recommended initial frequency": "daily after finance and inventory groups complete",
        "notes/risks": "This is a finalizer, not a source sync. Bad ordering gives stale value, not corrupt data.",
    },
    {
        "job name": "Sourcing listing availability",
        "command/script": "integrations/refresh_sourcing_listing_availability.py --apply --limit 250",
        "current group(s)": "daily; catalog",
        "reads tables": "sourcing_opportunities; sourcing_ebay_candidates; sourcing_settings",
        "writes tables": "sourcing_ebay_candidates; sourcing_opportunities; sourcing_actions",
        "external services used": "eBay Browse API; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {EBAY}",
        "must run after": "none",
        "should run after": "Matching intelligence refresh, if statuses should reflect newest sourcing runs",
        "must not overlap with": "itself; sourcing opportunity scoring/matching jobs",
        "safe to run independently": "yes",
        "safe to parallelize": "limited: avoid sourcing_opportunities writers",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental limited batch",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "sourcing-catalog",
        "recommended initial frequency": "daily or every 6 hours during buying windows",
        "notes/risks": "Bounded eBay Browse calls. Keeps stale/ended sourcing candidates from polluting buy decisions.",
    },
    {
        "job name": "Matching intelligence refresh",
        "command/script": "integrations/refresh_matching_intelligence.py --runs-per-mode 1",
        "current group(s)": "core; daily; catalog; purchases",
        "reads tables": "sourcing_runs; sourcing_actions; sourcing_opportunities; sourcing_ebay_candidates; sourcing_seed_asins; manual_item_matches; purchase_items; order_problem_cases; matching_intelligence_examples; vw_latest_keepa_product_snapshot",
        "writes tables": "matching_intelligence_examples; sourcing_listing_snapshots; sourcing_seller_intelligence; sourcing_opportunities; sourcing_runs",
        "external services used": "Supabase-only",
        "required secrets/env vars": COMMON_SUPABASE,
        "must run after": "Sourcing purchase matching, for latest positive match examples",
        "should run after": "Sourcing listing availability; Keepa active products",
        "must not overlap with": "itself; Sourcing purchase matching; Sourcing listing availability; scoring jobs",
        "safe to run independently": "yes, but broad for sourcing tables",
        "safe to parallelize": "limited: avoid sourcing writers and broad Supabase scans",
        "incremental vs bounded lookback vs broad/backfill-style": "bounded rebuild/rescore; contains delete/insert refresh steps",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "sourcing-catalog",
        "recommended initial frequency": "daily, off the hot purchase ingestion path",
        "notes/risks": "Currently included in core and daily; for AWS cost/load, move to a separate sourcing-catalog task unless purchasing freshness requires it.",
    },
    {
        "job name": "Keepa active products",
        "command/script": "integrations/keepa_sync_products.py --source amazon_active --limit 10 --batch-size 10 --stale-days 7 --min-tokens 100 --offers 20 --stock --no-history --write",
        "current group(s)": "catalog; repricing",
        "reads tables": "vw_latest_amazon_fba_inventory_snapshot; vw_latest_keepa_product_snapshot",
        "writes tables": "keepa_product_snapshots; optional keepa_product_history_points when --write-history and history enabled",
        "external services used": "Keepa; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {KEEPA}",
        "must run after": "Amazon FBA inventory",
        "should run after": "Amazon listing status, if active catalog and listing state should align",
        "must not overlap with": "any other Keepa job",
        "safe to run independently": "yes, with token guard",
        "safe to parallelize": "no with Keepa jobs; yes with unrelated low-load Supabase jobs",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental stale limited batch",
        "whether safe for AWS cloud mode": "yes, but token budget requires central scheduling",
        "recommended AWS orchestration group": "keepa-rolling-refresh",
        "recommended initial frequency": "every 2 hours with --limit 10 only if target cadence accepts ~120 ASIN/day; otherwise lower offers/stock or upgrade Keepa tokens",
        "notes/risks": "Observed active config consumed 98 tokens for 10 ASINs (~9.8/ASIN). With 5 token/min refill, this cannot refresh ~1,028 ASINs every 3/5/7 days using offers=20+stock.",
    },
    {
        "job name": "Keepa FBA prep pricing",
        "command/script": "integrations/keepa_sync_products.py --source received_fba_prep --batch-size 20 --min-tokens 25 --offers 20 --stock --no-history --write",
        "current group(s)": "fba-pricing",
        "reads tables": "purchase_items; vw_latest_keepa_product_snapshot",
        "writes tables": "keepa_product_snapshots; optional keepa_product_history_points when --write-history and history enabled",
        "external services used": "Keepa; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {KEEPA}",
        "must run after": "Receiving marks Amazon-bound items received; optional Amazon FBA inventory",
        "should run after": "Keepa active products only if token budget remains",
        "must not overlap with": "any other Keepa job",
        "safe to run independently": "yes, but current config can overrun tokens",
        "safe to parallelize": "no with Keepa jobs",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental FBA prep batch, currently no stale-days or limit in scheduler command",
        "whether safe for AWS cloud mode": "yes only after adding per-batch token checks or a safer limit",
        "recommended AWS orchestration group": "fba-pricing",
        "recommended initial frequency": "manual/on-demand during FBA prep, or hourly with --limit 5-10 and min-tokens >=100",
        "notes/risks": "Observed 20-ASIN batch consumed 228 tokens and the second 20-ASIN batch hit HTTP 429. Current scheduler command is too aggressive for 300 max/5 per minute token plan.",
    },
    {
        "job name": "Amazon Product Fees estimates",
        "command/script": "integrations/amazon_sync_fee_estimates.py",
        "current group(s)": "fba-pricing",
        "reads tables": "purchase_items; vw_latest_keepa_product_snapshot; amazon_fee_estimates",
        "writes tables": "amazon_fee_estimates",
        "external services used": "Amazon SP-API Product Fees; Supabase",
        "required secrets/env vars": f"{COMMON_SUPABASE}; {AMAZON_SPAPI}",
        "must run after": "Keepa active products or Keepa FBA prep pricing, so price points are current",
        "should run after": "RevSeller enrichment, if target_price contributes price point selection",
        "must not overlap with": "itself; other Product Fees jobs",
        "safe to run independently": "yes, if selected price points exist",
        "safe to parallelize": "limited: Product Fees v0 is rate-limited; avoid other SP-API heavy calls",
        "incremental vs bounded lookback vs broad/backfill-style": "incremental price-point fee cache",
        "whether safe for AWS cloud mode": "yes",
        "recommended AWS orchestration group": "fba-pricing",
        "recommended initial frequency": "hourly during FBA prep; daily otherwise",
        "notes/risks": "Should follow Keepa/price refresh. Observed 40 selected price points and 40 cached estimates.",
    },
]


def write_matrix() -> None:
    path = EXPORTS / "aws_scheduler_dependency_matrix.csv"
    fields = list(JOBS[0].keys())
    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=fields)
        writer.writeheader()
        writer.writerows(JOBS)


def write_summary() -> None:
    path = EXPORTS / "aws_scheduler_dependency_summary.md"
    lines = [
        "# AWS Scheduler Dependency Summary",
        "",
        "This analysis is based on `run_all_syncs.py`, the invoked integration scripts, system-health routes, and the captured instrumentation run from `20260620-080136`. No production jobs were run for this review.",
        "",
        "## Recommended AWS Shape",
        "",
        "| Group | Jobs | Cadence | Dependency notes |",
        "| --- | --- | --- | --- |",
        "| purchase-ingestion | eBay buyer purchases -> Sourcing purchase matching | hourly workday; 2-4h off-hours | Root purchase source. Avoid overlap with inbound shipment writers. |",
        "| purchase-tracking | EasyPost shipments | hourly | Must follow eBay purchase ingestion. Webhook-driven later. |",
        "| returns-and-order-problems | eBay order problem returns/inquiries -> EasyPost order problem returns | every 2-4h | eBay problem sync creates/updates cases; EasyPost return tracking follows. |",
        "| purchase-enrichment | RevSeller enrichment; Keepa missing purchase titles | hourly/2h, token-aware | Follows eBay purchases. Keepa title fill should not overlap other Keepa jobs. |",
        "| amazon-sales-recent | Amazon sales orders -> Recent Amazon sales finances -> Veeqo labels -> Recent sales profitability | hourly/2h | Keep this as a sequential chain. Profitability must follow orders/finance; labels should precede final profitability when possible. |",
        "| amazon-sales-fee-repair | Missing-fee finances -> missing-fee profitability | daily | Separate from recent chain to avoid SP-API finance overlap. |",
        "| fba-inventory-daily | Amazon FBA inventory; Amazon inventory planning | daily | Feeds reconciliation, listing status, business value, and repricing views. |",
        "| fba-shipments | Amazon FBA shipments -> FBA EasyPost carrier tracking | 2-4h while active; daily otherwise | Keep separate from receiving/purchases. Tracking follows shipment sync. |",
        "| reconciliation | Inventory reconciliation | after purchase/FBA source groups | Use skip-if-unchanged for frequent runs; avoid overlapping broad audits. |",
        "| finance-daily | YNAB transactions; YNAB cash balance; Amazon finance balances | daily | Must finish before business value snapshot. |",
        "| business-value-finalizer | Business value snapshot | daily after finance and reconciliation | Finalizer. Depends on latest inventory_positions, Amazon finance, YNAB cash. |",
        "| repricing-catalog | Amazon listing status; Informed repricing reports | daily | Listing status should follow FBA inventory. Informed is report/polling based. |",
        "| sourcing-catalog | Sourcing listing availability; Matching intelligence refresh | daily or 6h for availability | Move matching intelligence out of the hot core path unless buying workflow requires immediate refresh. |",
        "| keepa-rolling-refresh | Keepa active products | token-paced rolling schedule | Do not overlap any Keepa job. Current offers+stock config is too token-heavy for 1,028 ASIN refresh targets. |",
        "| fba-pricing | Keepa FBA prep pricing -> Amazon Product Fees estimates | on-demand/hourly during prep | Keepa FBA prep must be token-limited; fee estimates follow fresh price points. |",
        "| audits | finance-audit; listing-audit; inventory-audit | manual or weekly off-hours | Do not mix with normal scheduled freshness jobs. |",
        "",
        "## Critical Ordering",
        "",
        "- eBay buyer purchases must precede EasyPost shipments and sourcing purchase matching.",
        "- eBay order problem returns/inquiries should precede EasyPost order problem returns.",
        "- Amazon sales orders must precede Amazon sales finances, which must precede sales profitability.",
        "- Veeqo label costs should complete before final profitability when MF label cost precision matters.",
        "- Amazon FBA inventory should precede Amazon listing status and inventory reconciliation.",
        "- Amazon FBA shipments should precede FBA EasyPost carrier tracking.",
        "- Inventory reconciliation, YNAB cash balance, and Amazon finance balances should precede business value snapshot.",
        "- Keepa jobs must not overlap each other on the current token plan.",
        "",
        "## System Health Implications",
        "",
        "- `run_all_syncs.py` writes local `logs/sync_health.json`, `logs/sync_runs.jsonl`, and uses `logs/run_all_syncs.lock` for overlap protection.",
        "- `/api/system-health` combines Supabase freshness signals with local log files. In cloud mode, local file signals become unavailable unless replaced by a cloud-visible sync ledger.",
        "- `/api/sync-refresh` starts local `run_all_syncs.py` groups and refuses to start when the local lock is active. In AWS, replace this with an ECS task invocation or disable local execution.",
        "- Existing health cadences are coarse: core is expected every 12h and daily every 24h. AWS groups should expose their own health records rather than relying only on old group names.",
        "",
        "## Main Risks",
        "",
        "- Supabase load: FBA inventory snapshots, listing audits, inventory reconciliation, matching intelligence, and profitability audits are broad/read-heavy or high-write jobs. Do not run these together on constrained Supabase IO.",
        "- Amazon SP-API quotas: sales finances, FBA inventory, listing status/audit, inventory planning, and fee estimates should be separated by endpoint family where practical.",
        "- EasyPost: polling is bounded and has 429 backoff, but active tracking should eventually move to webhooks.",
        "- Keepa: current active listing refresh configuration costs roughly 9.8 tokens/ASIN observed; FBA prep observed 11.4 tokens/ASIN and hit 429 on the second batch.",
        "- Local files: RevSeller diagnostics and sync health logs are local-machine artifacts unless redirected to S3/CloudWatch/Supabase.",
        "",
        "## Per-Job Detail",
        "",
    ]
    for job in JOBS:
        lines.extend(
            [
                f"### {job['job name']}",
                "",
                f"- Command: `{job['command/script']}`",
                f"- Current groups: {job['current group(s)']}",
                f"- Reads: {job['reads tables']}",
                f"- Writes: {job['writes tables']}",
                f"- Must run after: {job['must run after']}",
                f"- Must not overlap with: {job['must not overlap with']}",
                f"- AWS group/frequency: {job['recommended AWS orchestration group']} / {job['recommended initial frequency']}",
                f"- Parallelization: {job['safe to parallelize']}",
                f"- Cloud mode: {job['whether safe for AWS cloud mode']}",
                f"- Notes: {job['notes/risks']}",
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")


def write_keepa_plan() -> None:
    path = EXPORTS / "keepa_active_listing_refresh_plan.md"
    active_asins = 1028
    observed_tokens_per_asin = 9.8
    tokens_per_day = 5 * 60 * 24
    max_tokens = 300
    total_tokens = active_asins * observed_tokens_per_asin
    full_refresh_hours = total_tokens / (5 * 60)
    lines = [
        "# Keepa Active Listing Refresh Plan",
        "",
        "## Current Implementation",
        "",
        "`integrations/keepa_sync_products.py` uses `KeepaClient.get_products()` with these parameters for the scheduled active-products job:",
        "",
        "```text",
        "domain=1",
        "asin=<comma-separated batch>",
        "stats=90",
        "history=0",
        "rating=1",
        "wait=1",
        "offers=20",
        "stock=1",
        "```",
        "",
        "The scheduled command is:",
        "",
        "```text",
        "integrations/keepa_sync_products.py --source amazon_active --limit 10 --batch-size 10 --stale-days 7 --min-tokens 100 --offers 20 --stock --no-history --write",
        "```",
        "",
        "Source selection for `amazon_active` reads `vw_latest_amazon_fba_inventory_snapshot` and includes ASINs with positive current quantity, then filters to ASINs with no Keepa snapshot or a latest snapshot older than `--stale-days`, ordered oldest first. It writes `keepa_product_snapshots`; `keepa_product_history_points` are written only when `--write-history` is passed and history is requested.",
        "",
        "## Observed Token Behavior",
        "",
        "- Active-products run on 2026-06-20: 10 ASINs, tokens before 300, tokens after 202. Observed cost: 98 tokens total, about 9.8 tokens/ASIN.",
        "- FBA prep pricing run on 2026-06-20: first 20-ASIN batch, tokens before 207, tokens after -21. Observed cost: 228 tokens total, about 11.4 tokens/ASIN; the next 20-ASIN batch immediately hit HTTP 429.",
        "- Keepa refill observed in logs: 5 tokens/minute with 300 max tokens.",
        "- The current code stores `payload.tokenFlowReduction` into each snapshot row as `token_cost`. That value appears to be response/batch-level, so it should not be treated as exact per-ASIN cost until the code normalizes it, for example `tokenFlowReduction / returned_products` plus run-level token-before/token-after.",
        "",
        "## Parameter Effects",
        "",
        "- `stats=90` is what gives current/avg30/avg90/avg180 arrays and sales-rank drop counters in `product.stats`. The current implementation reads current Buy Box, 90-day Buy Box, current new/FBA/new/used prices, sales rank averages, and `salesRankDrops30/90/180` from this stats payload.",
        "- `--no-history` sets `history=0`. This avoids returning full `csv` history arrays and prevents history point parsing/writes. It reduces payload size and Supabase write volume. It does not remove the `stats=90` summary fields that MBOP currently stores.",
        "- `--offers 20` requests live offer data. Combined with `--stock`, it materially increases observed token use. The 9.8-11.4 tokens/ASIN observed cost is far above a simple product/stats-only call and should be assumed to be driven mainly by offers/stock/rating extras.",
        "- `--stock` requests stock detail for offers and is explicitly documented in the script help as potentially costing extra tokens.",
        "- Sales frequency/rank drops do not require writing history rows in the current implementation; they are taken from `stats.salesRankDrops30`, `stats.salesRankDrops90`, and `stats.salesRankDrops180`. Full history is only needed if MBOP wants its own time-series analysis beyond Keepa's stats window.",
        "",
        "## Full Refresh Math",
        "",
        f"Using ~{active_asins:,} active Amazon listing ASINs and the observed active config cost of {observed_tokens_per_asin:.1f} tokens/ASIN:",
        "",
        f"- Tokens for one full refresh: about {total_tokens:,.0f}.",
        f"- Refill capacity: {tokens_per_day:,} tokens/day, but only 300 can be held at once.",
        f"- Minimum refill time for one full refresh: about {full_refresh_hours:.1f} hours of continuous refill.",
        "- Because max balance is 300 tokens, the refresh must be spread across small runs. Starting at 300 tokens helps only for the first run.",
        "",
        "## Rolling Cadence Feasibility",
        "",
        "| Target cadence | ASINs/day | Tokens/day at 9.8/ASIN | Feasible on 7,200 tokens/day refill? | Practical note |",
        "| --- | ---: | ---: | --- | --- |",
        f"| Every 3 days | {active_asins / 3:.0f} | {(active_asins / 3) * observed_tokens_per_asin:,.0f} | Yes by refill math | Requires about 34-35 ASINs/day. With batch 10, run 4 times/day. |",
        f"| Every 5 days | {active_asins / 5:.0f} | {(active_asins / 5) * observed_tokens_per_asin:,.0f} | Yes | Requires about 21 ASINs/day. With batch 10, run 3 times/day or 2 runs plus occasional catch-up. |",
        f"| Every 7 days | {active_asins / 7:.0f} | {(active_asins / 7) * observed_tokens_per_asin:,.0f} | Yes | Requires about 15 ASINs/day. With batch 10, run 2 times/day. |",
        "",
        "The limiting factor is not daily refill; it is burst size and overlapping jobs. A 20-ASIN offers+stock batch can consume more than 200 tokens and push the account below zero/429. Keep batch size at 10 or lower unless the code checks tokens between batches.",
        "",
        "## Recommended Strategy",
        "",
        "### Active Amazon Listings",
        "",
        "- Keep `--no-history` for routine refreshes.",
        "- For buy-opportunity detection, split into two Keepa modes:",
        "  - Light daily rolling mode: `stats=90`, `rating=1`, `history=0`, no `offers`, no `stock`, batch 20-50 after measuring token cost.",
        "  - Deep offer/stock mode: `--offers 20 --stock`, batch 5-10, used only for candidate ASINs needing offer-depth/stock intelligence.",
        "- If keeping the current deep config for all active listings, use `--batch-size 10`, `--limit 10`, `--min-tokens 150`, and run:",
        "  - every 6 hours for a 3-day target,",
        "  - every 8 hours for a 5-day target,",
        "  - every 12 hours for a 7-day target.",
        "- Never run active-products and FBA-prep Keepa jobs at the same time.",
        "- Add per-batch token checks before every product request. The current script checks `--min-tokens` only once before all batches.",
        "",
        "### FBA Prep Pricing",
        "",
        "- Change scheduled command to include a small limit, for example `--limit 5` or `--limit 10`, and `--min-tokens 150`.",
        "- Prefer on-demand/manual during shipment prep. Product Fees estimates should run after Keepa FBA prep pricing.",
        "- Current command without a limit selected 40 ASINs and hit 429. It is not safe as an unattended cloud scheduled task on the observed token plan.",
        "",
        "## Fields To Store",
        "",
        "For ongoing buy-opportunity detection, store or expose these fields from each refresh:",
        "",
        "- ASIN",
        "- current Buy Box price",
        "- 90-day average Buy Box price",
        "- current new price",
        "- 90-day average new price",
        "- current/new FBA price when available",
        "- current sales rank",
        "- 90-day average sales rank",
        "- sales rank drops over 30/90/180 days or normalized sales frequency",
        "- refresh timestamp",
        "- token cost, normalized per ASIN and run-level total",
        "- tokens before and after run/batch",
        "- source, e.g. `amazon_active`, `received_fba_prep`, `purchase_pre_listed`, `explicit`",
        "- request mode, e.g. `stats_only` vs `offers_stock`",
        "",
        "Current schema already stores many of these in `keepa_product_snapshots`: current/avg Buy Box, current prices, sales rank stats, drops, rating/review/offer count, raw payload, tokens_left, token_cost, source. The recommended improvement is to make token accounting explicit and distinguish source/mode more precisely.",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    EXPORTS.mkdir(parents=True, exist_ok=True)
    write_matrix()
    write_summary()
    write_keepa_plan()


if __name__ == "__main__":
    main()
