-- Unified daily sourcing coverage cycles.
-- Forward-only additive schema. Existing sourcing runs, batches, candidates,
-- opportunities, actions, and matches remain intact.

create table if not exists public.sourcing_coverage_cycles (
  coverage_cycle_id uuid primary key default gen_random_uuid(),
  cycle_number bigint generated by default as identity,
  status text not null default 'active',
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  total_eligible_asins integer not null default 0,
  priority_1_count integer not null default 0,
  priority_2_count integer not null default 0,
  priority_3_count integer not null default 0,
  searched_count integer not null default 0,
  remaining_count integer not null default 0,
  failed_count integer not null default 0,
  total_browse_calls integer not null default 0,
  total_candidates_found integer not null default 0,
  total_qualifying_opportunities integer not null default 0,
  total_hard_blocked integer not null default 0,
  total_profitability_rejects integer not null default 0,
  completion_percentage numeric not null default 0,
  last_run_id uuid references public.sourcing_runs(sourcing_run_id) on delete set null,
  last_stop_reason text,
  last_quota_reset_at timestamptz,
  raw_metrics_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sourcing_coverage_cycles_status_check
    check (status in ('active', 'completed', 'failed'))
);

create unique index if not exists sourcing_coverage_cycles_one_active_idx
  on public.sourcing_coverage_cycles (status)
  where status = 'active';

create index if not exists sourcing_coverage_cycles_status_started_idx
  on public.sourcing_coverage_cycles (status, started_at desc);

create table if not exists public.sourcing_coverage_cycle_items (
  cycle_item_id uuid primary key default gen_random_uuid(),
  coverage_cycle_id uuid not null references public.sourcing_coverage_cycles(coverage_cycle_id) on delete cascade,
  asin text not null,
  seller_sku text,
  amazon_title text,
  amazon_image_url text,
  priority_bucket text not null,
  priority_sort_date timestamptz,
  queue_position integer not null,
  processing_status text not null default 'pending',
  eligibility_reason text,
  last_sold_at timestamptz,
  last_purchased_at timestamptz,
  purchase_state text,
  inventory_need_level text,
  monthly_velocity numeric,
  current_inventory_units numeric,
  months_of_supply numeric,
  target_sale_price numeric,
  target_sale_price_source text,
  last_ebay_checked_at timestamptz,
  browse_calls_used integer not null default 0,
  candidate_count integer not null default 0,
  qualifying_opportunity_count integer not null default 0,
  retry_count integer not null default 0,
  last_error text,
  seed_snapshot_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sourcing_coverage_cycle_items_bucket_check
    check (priority_bucket in ('1_recently_sold', '2_purchased_not_sent', '3_catalog_remaining')),
  constraint sourcing_coverage_cycle_items_status_check
    check (processing_status in ('pending', 'searching', 'searched', 'retryable_failed', 'paused', 'skipped', 'ineligible'))
);

create unique index if not exists sourcing_coverage_cycle_items_cycle_asin_idx
  on public.sourcing_coverage_cycle_items (coverage_cycle_id, asin);

create unique index if not exists sourcing_coverage_cycle_items_queue_idx
  on public.sourcing_coverage_cycle_items (coverage_cycle_id, queue_position);

create index if not exists sourcing_coverage_cycle_items_status_idx
  on public.sourcing_coverage_cycle_items (coverage_cycle_id, processing_status, queue_position);

create index if not exists sourcing_coverage_cycle_items_bucket_idx
  on public.sourcing_coverage_cycle_items (coverage_cycle_id, priority_bucket, processing_status, queue_position);

alter table public.sourcing_runs
  add column if not exists coverage_cycle_id uuid references public.sourcing_coverage_cycles(coverage_cycle_id) on delete set null,
  add column if not exists stop_reason text,
  add column if not exists starting_browse_quota_limit integer,
  add column if not exists starting_browse_quota_count integer,
  add column if not exists starting_browse_quota_remaining integer,
  add column if not exists ending_browse_quota_remaining integer,
  add column if not exists browse_quota_reserve integer,
  add column if not exists browse_quota_reset_at timestamptz,
  add column if not exists asins_searched_this_run integer,
  add column if not exists cumulative_asins_searched integer,
  add column if not exists asins_remaining_in_cycle integer,
  add column if not exists priority_1_searched integer,
  add column if not exists priority_1_remaining integer,
  add column if not exists priority_2_searched integer,
  add column if not exists priority_2_remaining integer,
  add column if not exists priority_3_searched integer,
  add column if not exists priority_3_remaining integer,
  add column if not exists buy_now_opportunity_count integer,
  add column if not exists best_offer_opportunity_count integer,
  add column if not exists auction_opportunity_count integer,
  add column if not exists multi_unit_opportunity_count integer,
  add column if not exists hard_blocked_count integer,
  add column if not exists profitability_reject_count integer,
  add column if not exists duplicate_count integer,
  add column if not exists failed_asin_count integer,
  add column if not exists retryable_asin_count integer,
  add column if not exists coverage_percentage numeric,
  add column if not exists last_processed_queue_position integer;

alter table public.sourcing_seed_asins
  add column if not exists coverage_cycle_id uuid references public.sourcing_coverage_cycles(coverage_cycle_id) on delete set null,
  add column if not exists coverage_cycle_item_id uuid references public.sourcing_coverage_cycle_items(cycle_item_id) on delete set null,
  add column if not exists queue_position integer,
  add column if not exists priority_bucket text;

create index if not exists sourcing_runs_coverage_cycle_idx
  on public.sourcing_runs (coverage_cycle_id, started_at desc);

create index if not exists sourcing_seed_asins_coverage_cycle_idx
  on public.sourcing_seed_asins (coverage_cycle_id, queue_position);

grant all on table public.sourcing_coverage_cycles to service_role;
grant all on table public.sourcing_coverage_cycle_items to service_role;

comment on table public.sourcing_coverage_cycles is
'Durable daily sourcing coverage-cycle header. One active cycle represents one pass through eligible ASINs.';

comment on table public.sourcing_coverage_cycle_items is
'Durable per-ASIN sourcing queue and progress state for the unified daily coverage cycle.';
